name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

<<<<<<< HEAD
      - run: |
=======
      - name: Install dependencies
        run: |
>>>>>>> cd95714152bbca9b0d953230348be9820ced3bbb
          python -m pip install --upgrade pip
          pip install -r requirements.txt

<<<<<<< HEAD
      - run: ruff check src tests
=======
      - name: Lint (ruff)
        run: ruff check src --fix
>>>>>>> 577784b7a45da4ba89f09b33f249607d8f4c0e43

<<<<<<< HEAD
      - run: black --check src tests

      - run: bandit -r src
=======
      - name: Format check (black)
        run: black --check src tests
>>>>>>> cd95714152bbca9b0d953230348be9820ced3bbb

      - run: pytest --cov=src --cov-report=term-missing --cov-fail-under=80
